### ISSUE TITLE
Instructions for running your project ?

### ISSUE THREAD

**Issue by monk1337** [mckinziebrandon/DeepChatModels#10]
I am new into this and there are some files name main.py and others , can you give me instructions how to run and how to train your chatbot with datasets? 

Apart those question i want to build a domain specific chatbot means it answer questions realted to a domain like medical shop and also if user ask something else rather than medical products then it chat normally like a chatbot , How can i do this ?

Suppose user asked : 
user : I want medicine for fever.
bot : Here are available medicines for fever {medical shop api call and search medicine there}
{Now question is if i train bot for some FAQ then how call medical shop api between questions ?
Another example : 
User : can you show me flavor of cold-drinks ?
Bot : Here are available cold-drinks flavours {call medical shop api for keyword search}
{now how i call api in the middle of answer if user ask something realted to medical}

So my idea is : 

If user ask something realted to 'medical api or shop' ==> reply something like above examples
if user ask normal questions like 'how are you ?' , 'How  is weather?' , 'i am feeling bored','tell me a joke' something these types questions then just talk normally like a chatbot from any dialogue dataset. How can i do this ?

**Comment by mckinziebrandon** [comment]
The docstring of `main.py` provides some usage examples:

```
main.py: Train and/or chat with a bot. (work in progress).
Typical use cases:
    1.  Train a model specified by yaml config file, located at
        path_to/my_config.yml, where paths are relative to project root:
            ./main.py --config path_to/my_config.yml
    2.  Train using mix of yaml config and cmd-line args, with
        command-line args taking precedence over any values.
            ./main.py \
                --config path_to/my_config.yml \
                --model_params "{'batch_size': 32, 'optimizer': 'RMSProp'}"
    3.  Load a pretrained model that was saved in path_to/pretrained_dir,
        which is assumed to be relative to the project root.
            ./main.py --pretrained_dir path_to/pretrained_dir
```

Regarding your medical shop example, do you have a dataset ready to train on? Note that sequence-to-sequence models (the ones this project is based on) require a considerable number of training examples to produce good results. Typically hundreds of thousands, or millions. That would be a pretty big FAQ! Hah. For something that domain specific, you'd be better off using something like a retrieval-based model for response ranking. [Here is a nice blog post](http://www.wildml.com/2016/04/deep-learning-for-chatbots-part-1-introduction/) that goes over such models. 

For the other part of your question, you'd need some binary classifier to determine whether to use the domain-specific medical-shop-bot or the dialogue bot. An SVM trained on (sentence, T/F) pairs where the label is either True (sentence is related to medical) or False (sentence is not related to medical -- use dialogue bot) should do the trick. There are of course many ways to approach this that are outside the scope of this repository.

**Comment by mckinziebrandon** [comment]
Did that address your issue? I'm going to mark this as closed in a few days if no response.
